'use strict';

// WRXN onboard scaffold (wrxn-kernel-20) — the DETERMINISTIC half of the onboard skill's Step 3.
// Reads a filled aios-intake.md and scaffolds the Day-1 operator file set under context/. CLI-First:
// `wrxn onboard --root <ws>` runs this. Idempotent: re-running regenerates the context/ files from the
// current intake. It NEVER touches the seeded operator files (decisions/log.md, connections.md) — those
// are the operator's own, hand-edited.

const fs = require('fs');
const path = require('path');

const PLACEHOLDER = '[Your answer here]';

// Parse aios-intake.md into { Q1..Q7: <answer text> }.
function parseIntake(text) {
  const answers = {};
  let curQ = null;
  let buf = [];
  const flush = () => {
    if (curQ) answers[curQ] = buf.join('\n').trim();
    buf = [];
  };
  for (const line of String(text || '').split('\n')) {
    const m = line.match(/^##\s*Q(\d)\b/);
    if (m) {
      flush();
      curQ = `Q${m[1]}`;
      continue;
    }
    if (curQ) buf.push(line);
  }
  flush();
  return answers;
}

function filled(answer) {
  const a = (answer || '').trim();
  return a !== '' && a !== PLACEHOLDER;
}

// The Day-1 context files and which intake answers feed each.
const CONTEXT_FILES = [
  { name: 'about-me.md', title: 'About me', from: ['Q1'] },
  { name: 'about-business.md', title: 'About the business', from: ['Q4', 'Q5'] },
  { name: 'priorities.md', title: 'Priorities (90 days)', from: ['Q3'] },
];

/**
 * Scaffold the Day-1 operator file set under <root>/context/ from <root>/aios-intake.md.
 * Returns { scaffolded: string[], skipped: string[] } (paths relative to root). Throws if the
 * intake is absent (run inside a workspace install, or pass an explicit --root).
 */
function scaffold(root) {
  const intakePath = path.join(root, 'aios-intake.md');
  let intakeText;
  try {
    intakeText = fs.readFileSync(intakePath, 'utf8');
  } catch {
    throw new Error('aios-intake.md not found — run inside a wrxn workspace install (wrxn init --workspace)');
  }

  const answers = parseIntake(intakeText);
  const ctxDir = path.join(root, 'context');
  fs.mkdirSync(ctxDir, { recursive: true });

  const scaffolded = [];
  const skipped = [];
  for (const file of CONTEXT_FILES) {
    const sections = file.from
      .filter((q) => filled(answers[q]))
      .map((q) => `## ${q}\n\n${answers[q].trim()}`);
    if (sections.length === 0) {
      skipped.push(path.join('context', file.name)); // no filled answer for this file yet
      continue;
    }
    const body = [`# ${file.title}`, '', '<!-- generated by `wrxn onboard` from aios-intake.md -->', '', ...sections, ''].join('\n');
    fs.writeFileSync(path.join(ctxDir, file.name), body);
    scaffolded.push(path.join('context', file.name));
  }

  return { scaffolded, skipped };
}

module.exports = { scaffold, parseIntake, filled, CONTEXT_FILES, PLACEHOLDER };
